version: '3'

services:
    web-server:
        image: nginx
        volumes:
            - ./config/nginx/site-enabled/default:/etc/nginx/conf.d/default.conf
            - ./www:/var/www
        ports:
            - 8069:8082
